### ISSUE TITLE
tar permission problems

### ISSUE THREAD

**Issue by jcgregorio** [jcgregorio/httplib2#241]
_From [schw...@gmail.com](https://code.google.com/u/102101513984015207006/) on March 13, 2013 21:04:00_

The permissions changed on the egg directory.  They need a chmod u+r.  This change to 0.8.0 causes fink to install an unreadable egg dir.  I'm on mac osx 10.8.

ls -la python2/httplib2.egg-info/
total 32
drwxr-x---  6 schwehr  staff   204 Mar  6 12:40 .
drwxr-x---  6 schwehr  staff   204 Mar  6 12:40 ..
-rw-r-----  1 schwehr  staff  2337 Mar  6 12:40 PKG-INFO
-rw-r-----  1 schwehr  staff   787 Mar  6 12:40 SOURCES.txt
-rw-r-----  1 schwehr  staff     1 Mar  6 12:40 dependency_links.txt
-rw-r-----  1 schwehr  staff     9 Mar  6 12:40 top_level.txt

When installed, this happens:
ls -l /sw/lib/python2.7/site-packages/httplib2-0.8-py2.7.egg-info/
total 32
-rw-r-----  1 root  admin  2337 Mar 13 17:55 PKG-INFO
-rw-r-----  1 root  admin   787 Mar 13 17:55 SOURCES.txt
-rw-r-----  1 root  admin     1 Mar 13 17:55 dependency_links.txt
-rw-r-----  1 root  admin     9 Mar 13 17:55 top_level.txt

/sw/bin/python2.7 setup.py build
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup
  File "/sw/lib/python2.7/site-packages/setuptools/__init__.py", line 2, in <module>
    from setuptools.extension import Extension, Library
  File "/sw/lib/python2.7/site-packages/setuptools/extension.py", line 5, in <module>
    from setuptools.dist import _get_unpatched
  File "/sw/lib/python2.7/site-packages/setuptools/dist.py", line 6, in <module>
    from setuptools.command.install import install
  File "/sw/lib/python2.7/site-packages/setuptools/command/__init__.py", line 8, in <module>
    from setuptools.command import install_scripts
  File "/sw/lib/python2.7/site-packages/setuptools/command/install_scripts.py", line 3, in <module>
    from pkg_resources import Distribution, PathMetadata, ensure_directory
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 2825, in <module>
    add_activation_listener(lambda dist: dist.activate())
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 710, in subscribe
    callback(dist)
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 2825, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 2257, in activate
    self.insert_on(path)
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 2364, in insert_on
    self.check_version_conflict()
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 2403, in check_version_conflict
    for modname in self._get_metadata('top_level.txt'):
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 2251, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 1219, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 1211, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/sw/lib/python2.7/site-packages/pkg_resources.py", line 1326, in _get
    stream = open(path, 'rb')
IOError: [Errno 13] Permission denied: '/sw/lib/python2.7/site-packages/httplib2-0.8-py2.7.egg-info/top_level.txt'
### execution of /tmp/fink.xTMpz failed, exit code 1

_Original issue: http://code.google.com/p/httplib2/issues/detail?id=251_

**Comment by 0-wiz-0** [comment]
What was the solution? I see this with the 0.9.2 tarball.

**Comment by jayvdb** [comment]
http://bitworking.org/news/2016/03/an_update_on_httplib2
