### ISSUE TITLE
testUpdatePatchUsesCachedETag test failure in 0.9.1, 0.9, and master

### ISSUE THREAD

**Issue by ddriddle** [jcgregorio/httplib2#301]
I am receiving a test error that effects httplib2-0.9.1, httplib2-0.9, and the code in master:

# httplib2-0.9.1
```
ddriddle@sdg-py27-dev:~/src/httplib2-0.9.1/python2$ python httplib2test.py 
..........................................................................................................F..................
======================================================================
FAIL: testUpdatePatchUsesCachedETag (__main__.HttpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "httplib2test.py", line 1034, in testUpdatePatchUsesCachedETag
    self.assertEqual(response.status, 200)
AssertionError: 405 != 200

----------------------------------------------------------------------
Ran 125 tests in 21.934s

FAILED (failures=1)
```
# master
```
ddriddle@sdg-py27-dev:~/src/httplib2/python2$ python httplib2test.py 
..........................................................................................................F..................
======================================================================
FAIL: testUpdatePatchUsesCachedETag (__main__.HttpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "httplib2test.py", line 1034, in testUpdatePatchUsesCachedETag
    self.assertEqual(response.status, 200)
AssertionError: 405 != 200

----------------------------------------------------------------------
Ran 125 tests in 20.538s

FAILED (failures=1)
```

**Comment by jcgregorio** [comment]
That's an error with the server the test runs against, not with the library itself. You can safely ignore those failures.
